### ISSUE TITLE
Molasses disappears when leaving the Benbow Inn

### ISSUE THREAD

**Issue by Thunderforge** [elasota/mti-bugs#6] opened 2023-06-11 03:35 UTC
While escaping the Benbow Inn, your vision is covered by molasses. However, it disappears and partially reappears when the song begins.

## Expected sequence.

1. Rizzo falls in the molasses
2. Your vision is completely covered by molasses
3. The song lyrics appear
4. A fade to black
5. Scene transition to Bristol
6. Molasses-vision continues along with song lyrics

## Actual sequence

1. Rizzo falls in the molasses
2. Your vision is completely covered by molasses
![Molasses Screen](https://github.com/elasota/mti-bugs/assets/6200170/db1205fc-09cb-4151-a002-f6581f032e09)
3. Your vision clears
![No Molasses](https://github.com/elasota/mti-bugs/assets/6200170/fed55394-7fe2-4f0c-8236-7724464f7a5f)
4. The song lyrics appear with a molasses background, but the rest of the screen is visible
![Molasses Wrong](https://github.com/elasota/mti-bugs/assets/6200170/ac93e8fd-f0c2-4eea-a0a9-6c68bb84b9ff)
5. A fade to black
7. Scene transition to Bristol
8. Molasses-vision and song lyrics appear as expected
![Molasses Right](https://github.com/elasota/mti-bugs/assets/6200170/ca258452-68e5-457c-9b19-c94aca9afae0)

## Versions Tested
* *Muppet Treasure Island* for Windows
* ScummVM Daily 2023-06-10

**Comment by elasota** [comment] 2023-06-11 04:10
Duplicate of #3

**Closed as completed by elasota** 2023-06-11 04:10 UTC

**Comment by Thunderforge** [comment] 2023-06-11 05:50
@elasota Isn't #3 is about the wipeoff sequence in Bristol not working? The bug I'm reporting is that before in the Benbow Inn it disappears early and the lyrics show over it.

**Comment by elasota** [comment] 2023-06-14 02:39
Yeah I'm just treating at as one bug for the whole sequence.  There are numerous points where the molasses disappears.
